/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/widgets/PageImageUrl'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PageImageUrl'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.DocumentImageUrls = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.PageImageUrl);
  }
}(this, function(ApiClient, PageImageUrl) {
  'use strict';




  /**
   * The DocumentImageUrls model module.
   * @module model/widgets/DocumentImageUrls
   * @version 6.0.0
   */

  /**
   * Constructs a new <code>DocumentImageUrls</code>.
   * @alias module:model/widgets/DocumentImageUrls
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DocumentImageUrls</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/widgets/DocumentImageUrls} obj Optional instance to populate.
   * @return {module:model/widgets/DocumentImageUrls} The populated <code>DocumentImageUrls</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('imageSize')) {
        obj['imageSize'] = ApiClient.convertToType(data['imageSize'], 'String');
      }
      if (data.hasOwnProperty('imageURLs')) {
        obj['imageURLs'] = ApiClient.convertToType(data['imageURLs'], [PageImageUrl]);
      }
      if (data.hasOwnProperty('imagesAvailable')) {
        obj['imagesAvailable'] = ApiClient.convertToType(data['imagesAvailable'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * ImageSize corresponding to the imageUrl returned 
   * @member {module:model/widgets/DocumentImageUrls.ImageSizeEnum} imageSize
   */
  exports.prototype['imageSize'] = undefined;
  /**
   * A list of image url (one per page).
   * @member {Array.<module:model/widgets/PageImageUrl>} imageURLs
   */
  exports.prototype['imageURLs'] = undefined;
  /**
   * true if images for the associated image size is available, else false.
   * @member {Boolean} imagesAvailable
   */
  exports.prototype['imagesAvailable'] = undefined;


  /**
   * Allowed values for the <code>imageSize</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ImageSizeEnum = {
    /**
     * value: "FIXED_WIDTH_50px"
     * @const
     */
    "FIXED_WIDTH_50px": "FIXED_WIDTH_50px",
    /**
     * value: "FIXED_WIDTH_250px"
     * @const
     */
    "FIXED_WIDTH_250px": "FIXED_WIDTH_250px",
    /**
     * value: "FIXED_WIDTH_675px"
     * @const
     */
    "FIXED_WIDTH_675px": "FIXED_WIDTH_675px",
    /**
     * value: "ZOOM_50_PERCENT"
     * @const
     */
    "ZOOM_50_PERCENT": "ZOOM_50_PERCENT",
    /**
     * value: "ZOOM_75_PERCENT"
     * @const
     */
    "ZOOM_75_PERCENT": "ZOOM_75_PERCENT",
    /**
     * value: "ZOOM_100_PERCENT"
     * @const
     */
    "ZOOM_100_PERCENT": "ZOOM_100_PERCENT",
    /**
     * value: "ZOOM_125_PERCENT"
     * @const
     */
    "ZOOM_125_PERCENT": "ZOOM_125_PERCENT",
    /**
     * value: "ZOOM_150_PERCENT"
     * @const
     */
    "ZOOM_150_PERCENT": "ZOOM_150_PERCENT",
    /**
     * value: "ZOOM_200_PERCENT"
     * @const
     */
    "ZOOM_200_PERCENT": "ZOOM_200_PERCENT"  };


  return exports;
}));


