/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/agreements/DisplayParticipantInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DisplayParticipantInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.DisplayParticipantSetInfo = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.DisplayParticipantInfo);
  }
}(this, function(ApiClient, DisplayParticipantInfo) {
  'use strict';




  /**
   * The DisplayParticipantSetInfo model module.
   * @module model/agreements/DisplayParticipantSetInfo
   * @version 6.0.0
   */

  /**
   * Constructs a new <code>DisplayParticipantSetInfo</code>.
   * @alias module:model/agreements/DisplayParticipantSetInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>DisplayParticipantSetInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/agreements/DisplayParticipantSetInfo} obj Optional instance to populate.
   * @return {module:model/agreements/DisplayParticipantSetInfo} The populated <code>DisplayParticipantSetInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('displayUserSetMemberInfos')) {
        obj['displayUserSetMemberInfos'] = ApiClient.convertToType(data['displayUserSetMemberInfos'], [DisplayParticipantInfo]);
      }
      if (data.hasOwnProperty('displayUserSetName')) {
        obj['displayUserSetName'] = ApiClient.convertToType(data['displayUserSetName'], 'String');
      }
    }
    return obj;
  }

  /**
   * Displays the info about user set
   * @member {Array.<module:model/agreements/DisplayParticipantInfo>} displayUserSetMemberInfos
   */
  exports.prototype['displayUserSetMemberInfos'] = undefined;
  /**
   * The name of the display user set. Returned only, if the API caller is the sender of agreement. 
   * @member {String} displayUserSetName
   */
  exports.prototype['displayUserSetName'] = undefined;



  return exports;
}));


