/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.SendOptions = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SendOptions model module.
   * @module model/agreements/SendOptions
   * @version 6.0.0
   */

  /**
   * Constructs a new <code>SendOptions</code>.
   * @alias module:model/agreements/SendOptions
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SendOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/agreements/SendOptions} obj Optional instance to populate.
   * @return {module:model/agreements/SendOptions} The populated <code>SendOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('completionEmails')) {
        obj['completionEmails'] = ApiClient.convertToType(data['completionEmails'], 'String');
      }
      if (data.hasOwnProperty('inFlightEmails')) {
        obj['inFlightEmails'] = ApiClient.convertToType(data['inFlightEmails'], 'String');
      }
      if (data.hasOwnProperty('initEmails')) {
        obj['initEmails'] = ApiClient.convertToType(data['initEmails'], 'String');
      }
    }
    return obj;
  }

  /**
   * Control notification mails for agreement completion events - COMPLETED, CANCELLED, EXPIRED and REJECTED
   * @member {module:model/agreements/SendOptions.CompletionEmailsEnum} completionEmails
   */
  exports.prototype['completionEmails'] = undefined;
  /**
   * Control notification mails for agreement-in-process events - DELEGATED, REPLACED
   * @member {module:model/agreements/SendOptions.InFlightEmailsEnum} inFlightEmails
   */
  exports.prototype['inFlightEmails'] = undefined;
  /**
   * Control notification mails for Agreement initiation events - ACTION_REQUESTED and CREATED
   * @member {module:model/agreements/SendOptions.InitEmailsEnum} initEmails
   */
  exports.prototype['initEmails'] = undefined;


  /**
   * Allowed values for the <code>completionEmails</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CompletionEmailsEnum = {
    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL",
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE"  };

  /**
   * Allowed values for the <code>inFlightEmails</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InFlightEmailsEnum = {
    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL",
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE"  };

  /**
   * Allowed values for the <code>initEmails</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InitEmailsEnum = {
    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL",
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE"  };


  return exports;
}));


