/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.SupportingDocument = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SupportingDocument model module.
   * @module model/agreements/SupportingDocument
   * @version 6.0.0
   */

  /**
   * Constructs a new <code>SupportingDocument</code>.
   * @alias module:model/agreements/SupportingDocument
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>SupportingDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/agreements/SupportingDocument} obj Optional instance to populate.
   * @return {module:model/agreements/SupportingDocument} The populated <code>SupportingDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('displayLabel')) {
        obj['displayLabel'] = ApiClient.convertToType(data['displayLabel'], 'String');
      }
      if (data.hasOwnProperty('fieldName')) {
        obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('mimeType')) {
        obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
      }
      if (data.hasOwnProperty('numPages')) {
        obj['numPages'] = ApiClient.convertToType(data['numPages'], 'Number');
      }
      if (data.hasOwnProperty('participantId')) {
        obj['participantId'] = ApiClient.convertToType(data['participantId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Display name of the document
   * @member {String} displayLabel
   */
  exports.prototype['displayLabel'] = undefined;
  /**
   * The name of the supporting document field
   * @member {String} fieldName
   */
  exports.prototype['fieldName'] = undefined;
  /**
   * Id representing the document
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Mime-type of the document
   * @member {String} mimeType
   */
  exports.prototype['mimeType'] = undefined;
  /**
   * Number of pages in the document
   * @member {Number} numPages
   */
  exports.prototype['numPages'] = undefined;
  /**
   * The unique identifier of the participant that uploaded the supporting document
   * @member {String} participantId
   */
  exports.prototype['participantId'] = undefined;



  return exports;
}));


