/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/webhooks/WebhookAgreementEvents', 'model/webhooks/WebhookLibraryDocumentEvents', 'model/webhooks/WebhookMegaSignEvents', 'model/webhooks/WebhookWidgetEvents'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WebhookAgreementEvents'), require('./WebhookLibraryDocumentEvents'), require('./WebhookMegaSignEvents'), require('./WebhookWidgetEvents'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.WebhookConditionalParams = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.WebhookAgreementEvents, root.SwaggerJsClient.WebhookLibraryDocumentEvents, root.SwaggerJsClient.WebhookMegaSignEvents, root.SwaggerJsClient.WebhookWidgetEvents);
  }
}(this, function(ApiClient, WebhookAgreementEvents, WebhookLibraryDocumentEvents, WebhookMegaSignEvents, WebhookWidgetEvents) {
  'use strict';




  /**
   * The WebhookConditionalParams model module.
   * @module model/webhooks/WebhookConditionalParams
   * @version 6.0.0
   */

  /**
   * Constructs a new <code>WebhookConditionalParams</code>.
   * @alias module:model/webhooks/WebhookConditionalParams
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>WebhookConditionalParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/webhooks/WebhookConditionalParams} obj Optional instance to populate.
   * @return {module:model/webhooks/WebhookConditionalParams} The populated <code>WebhookConditionalParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('webhookAgreementEvents')) {
        obj['webhookAgreementEvents'] = WebhookAgreementEvents.constructFromObject(data['webhookAgreementEvents']);
      }
      if (data.hasOwnProperty('webhookLibraryDocumentEvents')) {
        obj['webhookLibraryDocumentEvents'] = WebhookLibraryDocumentEvents.constructFromObject(data['webhookLibraryDocumentEvents']);
      }
      if (data.hasOwnProperty('webhookMegaSignEvents')) {
        obj['webhookMegaSignEvents'] = WebhookMegaSignEvents.constructFromObject(data['webhookMegaSignEvents']);
      }
      if (data.hasOwnProperty('webhookWidgetEvents')) {
        obj['webhookWidgetEvents'] = WebhookWidgetEvents.constructFromObject(data['webhookWidgetEvents']);
      }
    }
    return obj;
  }

  /**
   * Conditional parameters for webhook agreement events
   * @member {module:model/webhooks/WebhookAgreementEvents} webhookAgreementEvents
   */
  exports.prototype['webhookAgreementEvents'] = undefined;
  /**
   * Conditional parameters for webhook library document events
   * @member {module:model/webhooks/WebhookLibraryDocumentEvents} webhookLibraryDocumentEvents
   */
  exports.prototype['webhookLibraryDocumentEvents'] = undefined;
  /**
   * Conditional parameters for webhook megasign events
   * @member {module:model/webhooks/WebhookMegaSignEvents} webhookMegaSignEvents
   */
  exports.prototype['webhookMegaSignEvents'] = undefined;
  /**
   * Conditional parameters for webhook widget events
   * @member {module:model/webhooks/WebhookWidgetEvents} webhookWidgetEvents
   */
  exports.prototype['webhookWidgetEvents'] = undefined;



  return exports;
}));


