/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
}(this, function(expect, SwaggerJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerJsClient.ReminderInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReminderInfo', function() {
    it('should create an instance of ReminderInfo', function() {
      // uncomment below and update the code to test ReminderInfo
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be.a(SwaggerJsClient.ReminderInfo);
    });

    it('should have the property firstReminderDelay (base name: "firstReminderDelay")', function() {
      // uncomment below and update the code to test the property firstReminderDelay
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property frequency (base name: "frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property lastSentDate (base name: "lastSentDate")', function() {
      // uncomment below and update the code to test the property lastSentDate
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property nextSentDate (base name: "nextSentDate")', function() {
      // uncomment below and update the code to test the property nextSentDate
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property recipientParticipantIds (base name: "recipientParticipantIds")', function() {
      // uncomment below and update the code to test the property recipientParticipantIds
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property reminderId (base name: "reminderId")', function() {
      // uncomment below and update the code to test the property reminderId
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property startReminderCounterFrom (base name: "startReminderCounterFrom")', function() {
      // uncomment below and update the code to test the property startReminderCounterFrom
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SwaggerJsClient.ReminderInfo();
      //expect(instance).to.be();
    });

  });

}));
