/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
}(this, function(expect, SwaggerJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerJsClient.MegaSignsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MegaSignsApi', function() {
    describe('createMegaSign', function() {
      it('should call createMegaSign successfully', function(done) {
        //uncomment below and update the code to test createMegaSign
        //instance.createMegaSign(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChildAgreementsInfoFile', function() {
      it('should call getChildAgreementsInfoFile successfully', function(done) {
        //uncomment below and update the code to test getChildAgreementsInfoFile
        //instance.getChildAgreementsInfoFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEvents', function() {
      it('should call getEvents successfully', function(done) {
        //uncomment below and update the code to test getEvents
        //instance.getEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSignChildAgreements', function() {
      it('should call getMegaSignChildAgreements successfully', function(done) {
        //uncomment below and update the code to test getMegaSignChildAgreements
        //instance.getMegaSignChildAgreements(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSignCombinedDocument', function() {
      it('should call getMegaSignCombinedDocument successfully', function(done) {
        //uncomment below and update the code to test getMegaSignCombinedDocument
        //instance.getMegaSignCombinedDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSignFormData', function() {
      it('should call getMegaSignFormData successfully', function(done) {
        //uncomment below and update the code to test getMegaSignFormData
        //instance.getMegaSignFormData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSignInfo', function() {
      it('should call getMegaSignInfo successfully', function(done) {
        //uncomment below and update the code to test getMegaSignInfo
        //instance.getMegaSignInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSignView', function() {
      it('should call getMegaSignView successfully', function(done) {
        //uncomment below and update the code to test getMegaSignView
        //instance.getMegaSignView(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMegaSigns', function() {
      it('should call getMegaSigns successfully', function(done) {
        //uncomment below and update the code to test getMegaSigns
        //instance.getMegaSigns(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMegaSignState', function() {
      it('should call updateMegaSignState successfully', function(done) {
        //uncomment below and update the code to test updateMegaSignState
        //instance.updateMegaSignState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
