/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerJsClient);
  }
}(this, function(expect, SwaggerJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerJsClient.WidgetsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WidgetsApi', function() {
    describe('createShareOnWidget', function() {
      it('should call createShareOnWidget successfully', function(done) {
        //uncomment below and update the code to test createShareOnWidget
        //instance.createShareOnWidget(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createWidget', function() {
      it('should call createWidget successfully', function(done) {
        //uncomment below and update the code to test createWidget
        //instance.createWidget(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllWidgetMembers', function() {
      it('should call getAllWidgetMembers successfully', function(done) {
        //uncomment below and update the code to test getAllWidgetMembers
        //instance.getAllWidgetMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEvents', function() {
      it('should call getEvents successfully', function(done) {
        //uncomment below and update the code to test getEvents
        //instance.getEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParticipantSet', function() {
      it('should call getParticipantSet successfully', function(done) {
        //uncomment below and update the code to test getParticipantSet
        //instance.getParticipantSet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetAgreements', function() {
      it('should call getWidgetAgreements successfully', function(done) {
        //uncomment below and update the code to test getWidgetAgreements
        //instance.getWidgetAgreements(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetAllDocumentsImageUrls', function() {
      it('should call getWidgetAllDocumentsImageUrls successfully', function(done) {
        //uncomment below and update the code to test getWidgetAllDocumentsImageUrls
        //instance.getWidgetAllDocumentsImageUrls(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetAuditTrail', function() {
      it('should call getWidgetAuditTrail successfully', function(done) {
        //uncomment below and update the code to test getWidgetAuditTrail
        //instance.getWidgetAuditTrail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetCombinedDocument', function() {
      it('should call getWidgetCombinedDocument successfully', function(done) {
        //uncomment below and update the code to test getWidgetCombinedDocument
        //instance.getWidgetCombinedDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetDocumentInfo', function() {
      it('should call getWidgetDocumentInfo successfully', function(done) {
        //uncomment below and update the code to test getWidgetDocumentInfo
        //instance.getWidgetDocumentInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetDocuments', function() {
      it('should call getWidgetDocuments successfully', function(done) {
        //uncomment below and update the code to test getWidgetDocuments
        //instance.getWidgetDocuments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetFormData', function() {
      it('should call getWidgetFormData successfully', function(done) {
        //uncomment below and update the code to test getWidgetFormData
        //instance.getWidgetFormData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetInfo', function() {
      it('should call getWidgetInfo successfully', function(done) {
        //uncomment below and update the code to test getWidgetInfo
        //instance.getWidgetInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetNoteForApiUser', function() {
      it('should call getWidgetNoteForApiUser successfully', function(done) {
        //uncomment below and update the code to test getWidgetNoteForApiUser
        //instance.getWidgetNoteForApiUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetSecurityOptionsForParticipation', function() {
      it('should call getWidgetSecurityOptionsForParticipation successfully', function(done) {
        //uncomment below and update the code to test getWidgetSecurityOptionsForParticipation
        //instance.getWidgetSecurityOptionsForParticipation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgetView', function() {
      it('should call getWidgetView successfully', function(done) {
        //uncomment below and update the code to test getWidgetView
        //instance.getWidgetView(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWidgets', function() {
      it('should call getWidgets successfully', function(done) {
        //uncomment below and update the code to test getWidgets
        //instance.getWidgets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidget', function() {
      it('should call updateWidget successfully', function(done) {
        //uncomment below and update the code to test updateWidget
        //instance.updateWidget(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidgetNoteForApiUser', function() {
      it('should call updateWidgetNoteForApiUser successfully', function(done) {
        //uncomment below and update the code to test updateWidgetNoteForApiUser
        //instance.updateWidgetNoteForApiUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidgetSecurityOptionsForParticipation', function() {
      it('should call updateWidgetSecurityOptionsForParticipation successfully', function(done) {
        //uncomment below and update the code to test updateWidgetSecurityOptionsForParticipation
        //instance.updateWidgetSecurityOptionsForParticipation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidgetState', function() {
      it('should call updateWidgetState successfully', function(done) {
        //uncomment below and update the code to test updateWidgetState
        //instance.updateWidgetState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWidgetVisibility', function() {
      it('should call updateWidgetVisibility successfully', function(done) {
        //uncomment below and update the code to test updateWidgetVisibility
        //instance.updateWidgetVisibility(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
